name: 'deployFunctions'

parameters:
- name: environment
  displayName: environment
  default: dev
  values: ["tst", "dev", "prd"]

trigger: none
pr: none

jobs:
- job: BuildAndDeploy
  steps:

  - task: PowerShell@2
    inputs:
      workingDirectory: Latitude/MTL
      targetType: 'inline'
      script: |
        Compress-Archive -Path * -DestinationPath $(Build.ArtifactStagingDirectory)/my-azure-function.zip
      pwsh: true

  - task: AzureCLI@2
    inputs:
      workingDirectory: MTL
      azureSubscription: $(subscription)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az functionapp deployment source config-zip -g "$(resource_group)" -n "$(functionapp)" --src $(Build.ArtifactStagingDirectory)/my-azure-function.zip
      addSpnToEnvironment: true
